server:
  port: 9110 #服务端口

spring:
  profiles:
    active: dev #环境设置
  application:
    name: infrastructure-apigateway #服务名

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true #gateway可以发现nacos中的微服务

      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/user/**, /*/edu/**

        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**

        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**

        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**

        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**

        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**

        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**

        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**

        - id: service-mail
          uri: lb://service-mail
          predicates:
            - Path=/*/mail/**